#%RAML 1.0 DataType
uses: 
  addressLib: address.lib.raml
type: object
properties:
  addressRowId? : string
  addressType: addressLib.addressType
  addressInfo: addressLib.addressInfo
  faInfo: addressLib.faInfo
  isVerified : boolean
  isDefault : boolean
  note : string
  venderInfoList: addressLib.venderInfo[]
  
    