#%RAML 1.0 NamedExample
phone.req.example:
value:
  phoneRowId : "2412"
  phoneType:
    code: "BUPH"
    value: "Home Phone"
  phoneInfo:
    intcode: "IND"
    phoneNumber : "7702354046"
  faInfo:
    office: "754"
    fa : "313"
  isVerified : true
  isDefault : true
  note : "this is phone details"
  venderInfoList:
    -
      vendorId: "361263"
      vendorName : "MSSB"
      verifiedDate: "2017/07/26"
      partyId : "27372122"
      verificationDesc : "verified"
    -
      vendorId: "361263"
      vendorName : "MSSB"
      verifiedDate: "2017/07/26"
      partyId : "27372122"
      verificationDesc : "verified"  