#%RAML 1.0 NamedExample
phone.res.example:
value:
  phoneRowId : "2412"
  statusInfo:
    httpStatus: "201"
    serviceStatus: "success"
    businessDesc: "Phone Record Rreated"
    technicalDesc: ""
    isRetry: false

