#%RAML 1.0
title: Phone API
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/11577a51-2e9f-4c5f-844e-20a8f8ceab2d/phone/api # baseUri: "http://localhost:80/phone/api"
version: v1
types:
  phoneInfoDetails: !include phone.res.dataType.raml
   
  
/phone:
  /{phoneNumber}:
    get:
      headers:  
        correlationId?: string
        appId?: string
        useCaseId?: string
        source?: string
        evenSource?: string
        
      responses:
        200:
          body:
            application/json:
              type: phoneInfoDetails
          
  