#%RAML 1.0 Library

types:
  phoneType:
    properties:
      code: string
      value: string
      
  phoneInfo:
    properties:
      intcode: string
      phoneNumber : string

  faInfo:
    properties:
      office: string
      fa : string

  venderInfo:
    properties:
      vendorId: string
      vendorName : string
      verifiedDate: string
      partyId : string
      verificationDesc : string
  
  transactionInfo:
    properties:
      appId: string
      correlationId: string
      useCaseId: string
      source: string
      evenSource: string
      requestTimestamp: datetime
      behalfOf: string  

  statusInfo:
    properties:
      httpStatus: string
      serviceStatus: string
      businessDesc: string
      technicalDesc: string
      isRetry: boolean


  