#%RAML 1.0 DataType
uses: 
  emailLib: email.lib.raml
type: object
properties:
  emailRowId? : string
  emailType?: emailLib.emailType
  emailId?: string
  faInfo?: emailLib.faInfo
  isVerified? : boolean
  isDefault? : boolean
  note? : string
  venderInfoList?: emailLib.venderInfo[]
  