#%RAML 1.0 NamedExample
phone.error.example:
value:
  statusInfo:
    httpStatus: "401"
    serviceStatus: "Error"
    businessDesc: ""
    technicalDesc: "downstream system not available"
    isRetry: false